# Generated by Django 2.2 on 2021-06-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreders',
            new_name='orders',
        ),
    ]
