# Generated by Django 2.2 on 2021-06-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='review_user',
        ),
    ]
